"""create_import_product_model

Revision ID: 0dc3fed8abc3
Revises: b994cf3ab590
Create Date: 2025-10-13 12:03:50.159904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc3fed8abc3'
down_revision: Union[str, Sequence[str], None] = 'b994cf3ab590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('grouped_products_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'grouped_products_config')
    # ### end Alembic commands ###
