"""update_role_table

Revision ID: 0e5563ac2794
Revises: b10b84f2f680
Create Date: 2025-10-14 11:46:38.914994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '0e5563ac2794'
down_revision: Union[str, Sequence[str], None] = 'b10b84f2f680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_product', 'carts', ['user_id', 'product_id'])
    op.add_column('roles', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True))
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.execute("UPDATE roles SET slug = CONCAT(LOWER(REPLACE(name, ' ', '-')), '-', id)")
    op.alter_column('roles', 'slug', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_column('roles', 'slug')
    op.drop_constraint('uix_user_product', 'carts', type_='unique')
    # ### end Alembic commands ###
