"""create variation_options table

Revision ID: 0ea8c1987c29
Revises: c25730af433a
Create Date: 2025-10-05 18:40:41.313627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '0ea8c1987c29'
down_revision: Union[str, Sequence[str], None] = 'c25730af433a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variation_options',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.Column('price', sa.String(length=191), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=191), nullable=False, server_default='en'),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('is_disable', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('sku', sa.String(length=191), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=False, server_default='false'),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='variation_options_product_id_fkey', ondelete='CASCADE')
)
    # ### end Alembic commands ###
    
    op.create_index('ix_variation_options_product_id', 'variation_options', ['product_id'], unique=False)
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variation_options_product_id'), table_name='variation_options')
    op.drop_table('variation_options')
    # ### end Alembic commands ###
