"""categories added

Revision ID: 115650bd0764
Revises: 9a804fdf221d
Create Date: 2025-09-17 09:24:19.746985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "115650bd0764"
down_revision: Union[str, Sequence[str], None] = "9a804fdf221d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    )
    op.add_column(
        "categories",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    )
    op.add_column("categories", sa.Column("level", sa.Integer(), nullable=False))
    op.add_column(
        "categories",
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
    )
    op.add_column(
        "categories",
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    )
    op.add_column("categories", sa.Column("image", sa.JSON(), nullable=True))
    op.add_column(
        "categories",
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "categories", sa.Column("admin_commission_rate", sa.Float(), nullable=True)
    )
    op.add_column("categories", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("categories", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_index(op.f("ix_categories_title"), table_name="categories")
    op.drop_column("categories", "description")
    op.drop_column("categories", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "categories",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_categories_title"), "categories", ["title"], unique=True)
    op.drop_column("categories", "deleted_at")
    op.drop_column("categories", "is_active")
    op.drop_column("categories", "admin_commission_rate")
    op.drop_column("categories", "details")
    op.drop_column("categories", "image")
    op.drop_column("categories", "icon")
    op.drop_column("categories", "language")
    op.drop_column("categories", "level")
    op.drop_column("categories", "slug")
    op.drop_column("categories", "name")
    # ### end Alembic commands ###
