"""remove_group_product

Revision ID: 16761de68842
Revises: 9244b77ba3d0
Create Date: 2025-10-16 14:36:09.546640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '16761de68842'
down_revision: Union[str, Sequence[str], None] = '9244b77ba3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_product', 'shops', ['shop_id'], ['id'])
    op.drop_column('order_product', 'grouped_items')
    op.drop_column('order_product', 'product_snapshot')
    op.drop_constraint('orders_shop_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'shop_id')
    op.drop_column('products', 'grouped_products_config')
    op.drop_column('products', 'grouped_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('grouped_products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('grouped_products_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_shop_id_fkey', 'orders', 'shops', ['shop_id'], ['id'])
    op.add_column('order_product', sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('order_product', sa.Column('grouped_items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_column('order_product', 'shop_id')
    