"""create_purchae_product_import_changes

Revision ID: 187f30b1cde4
Revises: 0dc3fed8abc3
Create Date: 2025-10-13 19:31:17.400916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187f30b1cde4'
down_revision: Union[str, Sequence[str], None] = '0dc3fed8abc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_purchased_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('total_sold_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_sold_quantity')
    op.drop_column('products', 'total_purchased_quantity')
    # ### end Alembic commands ###
