"""cart_variation_option_add

Revision ID: 1c6ec4aa3525
Revises: a64c783fda79
Create Date: 2025-10-25 14:06:12.533613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6ec4aa3525'
down_revision: Union[str, Sequence[str], None] = 'a64c783fda79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('variation_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carts', 'variation_options', ['variation_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'variation_option_id')
    # ### end Alembic commands ###
