"""enum order

Revision ID: 381927433838
Revises: 81f3cc9d2bfb
Create Date: 2025-10-08 14:56:29.910356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "381927433838"
down_revision: Union[str, Sequence[str], None] = "81f3cc9d2bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("order_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column("payment_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_status")
    op.drop_column("orders", "order_status")
    # ### end Alembic commands ###
