"""add_ratting_review_counts_in_products_table

Revision ID: 4cceddee42fc
Revises: a260d3183fa3
Create Date: 2025-12-16 16:39:18.809372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cceddee42fc'
down_revision: Union[str, Sequence[str], None] = 'a260d3183fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True,default=0.0))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True,default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'rating')