"""is_root field added in root

Revision ID: 5397a3e862d5
Revises: 20e2c9962b5a
Create Date: 2025-09-16 08:08:40.622400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5397a3e862d5'
down_revision: Union[str, Sequence[str], None] = '20e2c9962b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.add_column('users', sa.Column('is_root', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_root')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
