"""shipping email added

Revision ID: 5b0dd5fd667a
Revises: 61b173de4644
Create Date: 2025-10-02 22:26:38.238702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5b0dd5fd667a"
down_revision: Union[str, Sequence[str], None] = "61b173de4644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_template",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column(
            "subject", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_template_slug"), "email_template", ["slug"], unique=True
    )
    op.create_index("ix_emails_slug", "email_template", ["slug"], unique=True)
    op.create_table(
        "shipping_classes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "is_global", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum("FIXED", "PERCENTAGE", "FREE_SHIPPING", name="shippingtype"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipping_classes_slug"), "shipping_classes", ["slug"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shipping_classes_slug"), table_name="shipping_classes")
    op.drop_table("shipping_classes")
    op.drop_index("ix_emails_slug", table_name="email_template")
    op.drop_index(op.f("ix_email_template_slug"), table_name="email_template")
    op.drop_table("email_template")
    # ### end Alembic commands ###
