"""create faq table

Revision ID: 5b845c9ce567
Revises: e9323ee6489b
Create Date: 2025-10-09 14:10:11.242256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5b845c9ce567'
down_revision: Union[str, Sequence[str], None] = 'e9323ee6489b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('faqs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        
        # Primary Key
        sa.PrimaryKeyConstraint('id'),
        
        # Indexes
        sa.Index('ix_faqs_order', 'order'),
        sa.Index('ix_faqs_is_active', 'is_active'),
        sa.Index('ix_faqs_created_at', 'created_at')
    )
    
    # Full-text search index for better search performance
    op.execute("""
        CREATE INDEX idx_faqs_question_answer_fts ON faqs 
        USING gin(to_tsvector('english', question || ' ' || answer))
    """)
    
    # Unique index for question to prevent duplicates
    op.create_index('uq_faq_question', 'faqs', ['question'], unique=True)
    
    # Composite index for active ordered FAQs
    op.create_index('idx_faqs_active_ordered', 'faqs', ['is_active', 'order', 'created_at'])
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_faqs_active_ordered', table_name='faqs')
    op.drop_index('uq_faq_question', table_name='faqs')
    op.drop_index('idx_faqs_question_answer_fts', table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
