"""shipping email added

Revision ID: 61b173de4644
Revises: 0bbef801be97
Create Date: 2025-10-02 22:20:19.036977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b173de4644'
down_revision: Union[str, Sequence[str], None] = '0bbef801be97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_root_id'), 'categories', ['root_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_root_id'), table_name='categories')
    # ### end Alembic commands ###
