"""media back

Revision ID: 68282286e381
Revises: 53ca3a4a1912
Create Date: 2025-09-30 10:00:21.473964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68282286e381'
down_revision: Union[str, Sequence[str], None] = '53ca3a4a1912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_filename_key'), 'media', type_='unique')
    op.create_unique_constraint('uix_user_file', 'media', ['user_id', 'filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_file', 'media', type_='unique')
    op.create_unique_constraint(op.f('media_filename_key'), 'media', ['filename'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
