"""user shop issue

Revision ID: 732baa855dc0
Revises: 5762fcbef374
Create Date: 2025-09-10 08:18:33.688691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732baa855dc0'
down_revision: Union[str, Sequence[str], None] = '5762fcbef374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_shop_id', 'users', 'shops', ['shop_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_shop_id', 'users', type_='foreignkey')
    # ### end Alembic commands ###
