"""product added

Revision ID: 77a57e872201
Revises: 115650bd0764
Create Date: 2025-09-17 17:40:03.191311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "77a57e872201"
down_revision: Union[str, Sequence[str], None] = "115650bd0764"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sale_price", sa.Float(), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=True),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
        sa.Column(
            "bar_code", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("is_taxable", sa.Boolean(), nullable=False),
        sa.Column(
            "status", sa.Enum("PUBLISH", "DRAFT", name="productstatus"), nullable=False
        ),
        sa.Column(
            "product_type",
            sa.Enum("SIMPLE", "VARIABLE", name="producttype"),
            nullable=False,
        ),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column(
            "dimension_unit",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
        ),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.Column("video", sa.JSON(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_digital", sa.Boolean(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column(
            "external_product_url",
            sqlmodel.sql.sqltypes.AutoString(length=191),
            nullable=True,
        ),
        sa.Column(
            "external_product_button_text",
            sqlmodel.sql.sqltypes.AutoString(length=191),
            nullable=True,
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
