"""add_review_id_in_order_product_table

Revision ID: 87af15e4b3f2
Revises: 4cceddee42fc
Create Date: 2025-12-16 20:33:22.796309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87af15e4b3f2'
down_revision: Union[str, Sequence[str], None] = '4cceddee42fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column
    op.add_column('order_product', sa.Column('review_id', sa.Integer(), nullable=True))
    # Then add the foreign key constraint
    op.create_foreign_key('fk_order_product_review_id', 'order_product', 'reviews', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    op.drop_constraint('fk_order_product_review_id', 'order_product', type_='foreignkey')
    # Then drop the column
    op.drop_column('order_product', 'review_id')
    # ### end Alembic commands ###
