"""order added

Revision ID: 906bfc6449b8
Revises: 81f3cc9d2bfb
Create Date: 2025-10-07 07:17:34.703087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "906bfc6449b8"
down_revision: Union[str, Sequence[str], None] = "81f3cc9d2bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types manually if they don't exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderstatusenum') THEN
                CREATE TYPE orderstatusenum AS ENUM (
                    'PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED',
                    'CANCELLED', 'AT_LOCAL_FACILITY', 'OUT_FOR_DELIVERY',
                    'AT_DISTRIBUTION_CENTER', 'PACKED'
                );
            END IF;
        END$$;
    """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'paymentstatusenum') THEN
                CREATE TYPE paymentstatusenum AS ENUM (
                    'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REVERSAL',
                    'CASH_ON_DELIVERY', 'CASH', 'WALLET', 'AWAITING_APPROVAL'
                );
            END IF;
        END$$;
    """
    )

    # Drop defaults first
    op.alter_column("orders", "order_status", server_default=None)
    op.alter_column("orders", "payment_status", server_default=None)

    # Convert columns
    op.alter_column(
        "orders",
        "order_status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "REFUNDED",
            "FAILED",
            "CANCELLED",
            "AT_LOCAL_FACILITY",
            "OUT_FOR_DELIVERY",
            "AT_DISTRIBUTION_CENTER",
            "PACKED",
            name="orderstatusenum",
        ),
        nullable=True,
        postgresql_using="order_status::text::orderstatusenum",
    )

    op.alter_column(
        "orders",
        "payment_status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "PENDING",
            "PROCESSING",
            "SUCCESS",
            "FAILED",
            "REVERSAL",
            "CASH_ON_DELIVERY",
            "CASH",
            "WALLET",
            "AWAITING_APPROVAL",
            name="paymentstatusenum",
        ),
        nullable=True,
        postgresql_using="payment_status::text::paymentstatusenum",
    )

    # Reapply defaults
    op.alter_column(
        "orders", "order_status", server_default=sa.text("'PENDING'::orderstatusenum")
    )
    op.alter_column(
        "orders",
        "payment_status",
        server_default=sa.text("'PENDING'::paymentstatusenum"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "payment_status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "SUCCESS",
            "FAILED",
            "REVERSAL",
            "CASH_ON_DELIVERY",
            "CASH",
            "WALLET",
            "AWAITING_APPROVAL",
            name="paymentstatusenum",
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'payment-pending'::character varying"),
    )
    op.alter_column(
        "orders",
        "order_status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "REFUNDED",
            "FAILED",
            "CANCELLED",
            "AT_LOCAL_FACILITY",
            "OUT_FOR_DELIVERY",
            "AT_DISTRIBUTION_CENTER",
            "PACKED",
            name="orderstatusenum",
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'order-pending'::character varying"),
    )
    # ### end Alembic commands ###
