"""create_withdraw_shop

Revision ID: 9244b77ba3d0
Revises: 0e5563ac2794
Create Date: 2025-10-15 14:20:46.549902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '9244b77ba3d0'
down_revision: Union[str, Sequence[str], None] = '0e5563ac2794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_withdraw_requests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('admin_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED', 'FAILED', name='withdrawstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'CASH', 'DIGITAL_WALLET', name='paymentmethod'), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ifsc_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cash_handled_by', sa.Integer(), nullable=True),
    sa.Column('cash_payment_date', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cash_handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_withdraw_requests_shop_id'), 'shop_withdraw_requests', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_withdraw_requests_status'), 'shop_withdraw_requests', ['status'], unique=False)
    op.create_table('shop_earnings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('admin_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shop_earning', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_earnings_order_id'), 'shop_earnings', ['order_id'], unique=False)
    op.create_index(op.f('ix_shop_earnings_shop_id'), 'shop_earnings', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_earnings_shop_id'), table_name='shop_earnings')
    op.drop_index(op.f('ix_shop_earnings_order_id'), table_name='shop_earnings')
    op.drop_table('shop_earnings')
    op.drop_index(op.f('ix_shop_withdraw_requests_status'), table_name='shop_withdraw_requests')
    op.drop_index(op.f('ix_shop_withdraw_requests_shop_id'), table_name='shop_withdraw_requests')
    op.drop_table('shop_withdraw_requests')
    # ### end Alembic commands ###
