"""sync schema

Revision ID: 9a804fdf221d
Revises: 5397a3e862d5
Create Date: 2025-09-16 08:16:12.944028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a804fdf221d"
down_revision: Union[str, Sequence[str], None] = "5397a3e862d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("roles_name_key"), "roles", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("roles_name_key"), "roles", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
