"""add_table_transaction_logs

Revision ID: a260d3183fa3
Revises: d853e20f5324
Create Date: 2025-12-02 16:28:34.739940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a260d3183fa3'
down_revision: Union[str, Sequence[str], None] = 'd853e20f5324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variation_option_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_product_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('INCREASE', 'DECREASE', 'NO_CHANGE', name='transactiondirection'), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('previous_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_generated_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_details', sa.JSON(), nullable=True, server_default='{}'),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('requires_review', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_product_id'], ['order_product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variation_option_id'], ['variation_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_logs_product_id'), 'transaction_logs', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_reference_number'), 'transaction_logs', ['reference_number'], unique=False)
    op.create_index(op.f('ix_transaction_logs_transaction_date'), 'transaction_logs', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transaction_logs_transaction_type'), 'transaction_logs', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_transaction_type'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_transaction_date'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_reference_number'), table_name='transaction_logs')
    op.drop_index(op.f('ix_transaction_logs_product_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    # ### end Alembic commands ###
