"""db fetch update

Revision ID: a31b8692878d
Revises: 77a57e872201
Create Date: 2025-09-20 07:08:23.761512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31b8692878d'
down_revision: Union[str, Sequence[str], None] = '77a57e872201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=191),
               nullable=False)
    op.alter_column('products', 'dimension_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'dimension_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=191),
               nullable=True)
    # ### end Alembic commands ###
