"""password_reset_field_add_in_users_table

Revision ID: a64c783fda79
Revises: dbc11bf15b15
Create Date: 2025-10-23 18:54:54.188475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'a64c783fda79'
down_revision: Union[str, Sequence[str], None] = 'dbc11bf15b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True))
    op.add_column('users', sa.Column('password_reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_code_expires')
    op.drop_column('users', 'password_reset_code')
    # ### end Alembic commands ###
