"""update_order_and_order_product_table

Revision ID: c3f6c43a9f56
Revises: 1c6ec4aa3525
Create Date: 2025-11-04 19:20:19.208983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3f6c43a9f56'
down_revision: Union[str, Sequence[str], None] = '1c6ec4aa3525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('order_product', sa.Column('item_discount', sa.Float(), nullable=True))
    op.add_column('order_product', sa.Column('item_tax', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('coupon_discount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('tax_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shipping_classes', ['shipping_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'tax_classes', ['tax_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_id')
    op.drop_column('orders', 'tax_id')
    op.drop_column('orders', 'coupon_discount')
    op.drop_column('order_product', 'item_tax')
    op.drop_column('order_product', 'item_discount')
    op.drop_column('order_product', 'sale_price')
    # ### end Alembic commands ###
