"""attribute model

Revision ID: c7827aa07cf7
Revises: 68282286e381
Create Date: 2025-09-30 21:30:49.051069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c7827aa07cf7"
down_revision: Union[str, Sequence[str], None] = "68282286e381"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attributes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute_values",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("attribute_id", sa.Integer(), nullable=False),
        sa.Column(
            "value", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("meta", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute_product",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribute_value_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_values.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attribute_product")
    op.drop_table("attribute_values")
    op.drop_table("attributes")
    # ### end Alembic commands ###
