"""withdraw_request

Revision ID: c9c96c9c52b4
Revises: 16761de68842
Create Date: 2025-10-17 13:39:01.360984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c9c96c9c52b4'
down_revision: Union[str, Sequence[str], None] = '16761de68842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.add_column('shop_earnings', sa.Column('order_product_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_shop_earnings_order_product_id'), 'shop_earnings', ['order_product_id'], unique=False)
    op.create_foreign_key(None, 'shop_earnings', 'order_product', ['order_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_earnings', type_='foreignkey')
    op.drop_index(op.f('ix_shop_earnings_order_product_id'), table_name='shop_earnings')
    op.drop_column('shop_earnings', 'order_product_id')
    # ### end Alembic commands ###
