"""add_product_model_changes

Revision ID: d31cbd600689
Revises: 755c98009d5e
Create Date: 2025-10-11 13:41:01.676265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd31cbd600689'
down_revision: Union[str, Sequence[str], None] = '755c98009d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('grouped_products', sa.JSON(), nullable=True))
    op.add_column('variation_options', sa.Column('bar_code', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True))
    op.add_column('variation_options', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation_options', 'is_active')
    op.drop_column('variation_options', 'bar_code')
    op.drop_column('products', 'grouped_products')
    op.drop_column('products', 'attributes')
    # ### end Alembic commands ###
