"""unit optional

Revision ID: d3836ed8009c
Revises: 2d1601baaa2a
Create Date: 2025-09-26 20:58:03.869082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3836ed8009c'
down_revision: Union[str, Sequence[str], None] = '2d1601baaa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=191),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=191),
               nullable=False)
    # ### end Alembic commands ###
