"""create_tax_classes_table

Revision ID: dbc11bf15b15
Revises: 86bf4b8e6858
Create Date: 2025-10-18 16:46:17.882501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'dbc11bf15b15'
down_revision: Union[str, Sequence[str], None] = '86bf4b8e6858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_classes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('on_shipping', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_classes')
    # ### end Alembic commands ###
