"""update_faqs_table

Revision ID: e548e5dce841
Revises: c3f6c43a9f56
Create Date: 2025-11-16 10:48:01.220122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'e548e5dce841'
down_revision: Union[str, Sequence[str], None] = 'c3f6c43a9f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('faqs', 'question_type')
    # ### end Alembic commands ###
