"""index aply in manufacturer

Revision ID: efb3ddadec00
Revises: 89a61d1f5d10
Create Date: 2025-09-28 10:49:59.290498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb3ddadec00'
down_revision: Union[str, Sequence[str], None] = '89a61d1f5d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_manufacturers_slug'), 'manufacturers', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manufacturers_slug'), table_name='manufacturers')
    # ### end Alembic commands ###
