"""media update

Revision ID: f7959c44418d
Revises: 85d9bf42d97b
Create Date: 2025-09-30 09:27:05.650896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f7959c44418d"
down_revision: Union[str, Sequence[str], None] = "85d9bf42d97b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "media",
        sa.Column("extension", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "media",
        sa.Column("original", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("media", sa.Column("size_mb", sa.Float(), nullable=True))
    op.add_column(
        "media",
        sa.Column("thumbnail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("media", "media")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column(
            "media",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("media", "thumbnail")
    op.drop_column("media", "size_mb")
    op.drop_column("media", "original")
    op.drop_column("media", "extension")
    op.drop_column("media", "filename")
    # ### end Alembic commands ###
